### PR TITLE
Fix i18n support.

### PR DESCRIPTION
**Pull request by MeggyCal**
Although the string were translated, the translations were not expanded.

### CODE REVIEW

**Comment by aplanas** [comment]
@MeggyCal did you tested this? I plan to test it a bit later.

**Comment by MeggyCal** [comment]
> @MeggyCal did you tested this?

Yes, I tested this on my computer. It works for me and fixes the bugs I want to fix.

**Comment by aplanas** [comment]
There are some conflicts. Can you rebase?

**Comment by MeggyCal** [comment]
conflicts resolved

**Comment by aplanas** [comment]
Thanks!

**Comment by MeggyCal** [comment]
Thank you for taking care.

**Pull request merged**
